[package]
name = "intermediate_clijira"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0.143"
ellipse = "0.2.0"
itertools = "0.14.0"
io_utils = "0.3.2"

[dev-dependencies]
tempfile = "3.3.0"